Add new apps to the catalog
pluralsh/documentation pull request #75
Opened 2022-11-07 22:08 UTC by dherault

👍 

Added or modified: 
```js
  'airbyte',
  'console',
  'airflow',
  'argo-cd',
  'argo-workflows',
  'chatwoot',
  'crossplane',
  'dagster',
  'datahub',
  'etcd',
  'filecoin',
  'ghost',
  'gitlab',
  'grafana',
  'grafana-tempo',
  'growthbook',
  'hasura',
  'influx',
  'ingress-nginx',
  'istio',
  'jitsu',
  'kafka',
  'knative',
  'kserve',
  'kubecost',
  'kubeflow',
  'kubescape',
  'metabase',
  'minecraft',
  'minio',
  'mlflow',
  'mongodb',
  'mysql',
  'n8n',
  'nextcloud',
  'nocodb',
  'oncall',
  'plural',
  'postgres',
  'rabbitmq',
  'ray',
  'redis',
  'reloader',
  'rook',
  'sentry',
  'spark',
  'superset',
  'terraria',
  'touca',
  'trino',
  'valheim',
  'vault',
  'vaultwarden',
```

Missing:
- oncall
- grafana-tempo

For script failure reasons.

2022-11-07 22:15 UTC, dherault commented
Ohhhh, everything broke, need to speak with Michael about the script :/

2022-11-07 22:22 UTC, dherault commented
I fixed it 💪

2022-11-07 22:31 UTC, dherault commented
mmm @dogmar how do I add the new pages to the sidebar hierarchy?

2022-11-09 18:02 UTC, dogmar requested changes

2022-11-09 18:02 UTC, dogmar commented on pages/repositories/airbyte.md
> -```
@dherault These commands should be surrouned by a code fence.
````
```shell
{COMMAND}
```

2022-11-15 01:22 UTC, dherault commented
Closing in favor of @dogmar 's work

2022-11-15 01:22 UTC, closed without merging